version: '3.8'

services:
  hackudc25-front:
    image: hackudc25-front
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000